apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: create-ace-build-image-
spec:
  serviceAccountName: pipeline-deployer-serviceaccount
  params:
    - name: dockerfile-url
      value: https://raw.githubusercontent.com/ot4i/ace-docker/master/experimental/ace-full/Dockerfile.ubuntu
    - name: image-name
      value: image-registry.openshift-image-registry.svc:5000/pipeline-ace/ace-build-full:latest
  pipelineRef:
    name: pipeline-docker-build
  workspaces:
    - name: pipeline-shared-workspace
      volumeClaimTemplate:
        spec:
          storageClassName: ibmc-block-gold
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Mi
