apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: curl-to-workspace
spec:
  params:
    - name: url
      type: string
      description: URL of resource to download
    - name: output
      type: string
      description: location in the workspace to download to
  workspaces:
    - name: output
      description: workspace to save downloaded resource in
  steps:
    - name: curl
      image: docker.io/curlimages/curl:7.72.0@sha256:bd5bbd35f89b867c1dccbc84b8be52f3f74dea20b46c5fe0db3780e040afcb6f
      script: |
        #!/bin/sh
        curl -o /workspace/output/$(params.output) $(params.url)
        cat /workspace/output/$(params.output)
