apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: extend-ace-dockerfile
spec:
  params:
    - name: dockerfile
      type: string
      description: location of dockerfile to fix
      default: "Dockerfile"
  workspaces:
    - name: source
      description: workspace with dockerfile in
  steps:
    - name: sed
      image: alpine
      script: |
        #!/bin/sh
        echo "adding webkit2gtk to the libgtk2 dependencies as it is required for ACE v12"
        sed -i "s/libgtk2.0-0/libgtk2.0-0 webkit2gtk-driver/g" "/workspace/source/$(params.dockerfile)"
        cat /workspace/source/$(params.dockerfile)
